[package]
name = "asset_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.24"
notify = "8.2.0"
async-trait = "0.1"
tokio = {version = "1.48.0", features = ["full"]}
arc-swap = "1.7.1"
async-std = "*"